[project]
name = "imx500-webviewer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiohttp>=3.13.2",
    "aiortc>=1.14.0",
    "av>=16.0.1",
    "flask>=3.1.2",
    "modlib>=1.3.1",
    "munkres>=1.1.4",
]
